### ISSUE TITLE
Improve selection UI

### ISSUE THREAD

**Issue by daveih** [data4knowledge/study_definitions_workbench#12]
Improve the way the selection of studies works on the index page. Make the delete / view menu use less space. Also add button to each card to toggle the selection rather than clicking the whole card, cannot cut an dpaste text easily.

**Comment by dih-cdisc** [comment]
Moved selection to main nav bar and made menu dynamic based on 1 or more items selected

**Comment by dih-cdisc** [comment]
Reopen to change order of menu items
