### ISSUE TITLE
Images in Protocols

### ISSUE THREAD

**Issue by dih-cdisc** [data4knowledge/study_definitions_workbench#17]
I have been re-uploading the sponsor protocols in order to regenerate the FHIR files following your update to turn the images back on in the tool.  Unfortunately, even when I am VIEWING the M11 uploaded .docx files, I am not getting the images for ALL the protocols.

- Protocol A: has a couple of images, they along with adjacent text were highlighted in gray(as we discussed previously.)  I tried removing highlights before importing the .docx but no luck with the images showing up.
- Protocol B: This one has “NA” for the Trial Schema and maybe your code ONLY expects and image…but it would be good to surface any text when it is there.
- Protocol C: Again there is a lot of text along with tables in this Protocol for the Trial Schema (not an image pre se)

Names of protocols modifed as they are production.

**Comment by dih-cdisc** [comment]
Couple of tweaks added

- Included 1/2 in possible values for Phase
- Dump full section for section 1.2 not just images

For the particular protocols:

- Protocol A is using .emf images that are tricky to process.
- Protocol B: NA is the content for section 1.2 in that protocol
- Protocol C: Full section now dumped

**Comment by daveih** [comment]
Added a warning for non JPEG, PNG images

**Comment by daveih** [comment]
Built into v0.30.0
