### ISSUE TITLE
Protocol Page Menu

### ISSUE THREAD

**Issue by dih-cdisc** [data4knowledge/study_definitions_workbench#8]
When in "View Details" of a study and you have the "Views" menu on top.  Each time you pick a view, you still have the View drop down to navigate with.  However, once you choose the "Protocol" view from that drop down, you only have the "Sections" menu option and you then have to go back HOME if you want to relaunch the Detail to navigate through views again…

**Comment by daveih** [comment]
Updated menu structure in line with comments
