### ISSUE TITLE
M11 Document FHIR Import Address

### ISSUE THREAD

**Issue by dih-cdisc** [data4knowledge/study_definitions_workbench#9]
With the .docx protocol view the company name is listed but not the address.  (in the summary box and when listing selected studies for comparison)  while the imported FHIR JSON version lists the company name and address.

**Comment by dih-cdisc** [comment]
Updated to improve processing of the title page and handling of line breaks.

**Comment by dih-cdisc** [comment]
List page is not displaying the address. Also need to setup the address on M11 and FHIR imports

**Comment by daveih** [comment]
Addresses now being displayed.
